### PR TITLE
delete the old metric since the new one is being used in prometheus

### PR DESCRIPTION
**Pull request by nl-ria**
Now that https://github.com/Financial-Times/prometheus/pull/76 is merged, we can delete the old redundant metric.

### CODE REVIEW

**Comment by Limess** [comment]
Are:
1. Heimdall
2. Our Grafana dashboards
3. Other grafana dashboards (the one I know might be is Next radiator) still using the old one?

**Comment by nl-ria** [comment]
I have updated the Nagios ones in here : https://grafana.ft.com/d/z7pq4x2ik/system-status-drilldown?orgId=1 . Not so sure what the plan should be for Grafana  dashboards for *other* teams?

**Comment by nl-ria** [comment]
Did some follow-up with ETG. It doesnt look like we will affect the Next-Radiator Grafana board with this PR since they are not using any Nagios checks. Will need to update Grafana's [Next-Radiator](https://grafana.ft.com/d/000000235/next-radiator?orgId=1) with the Health-check one

**Comment by Limess** [comment]
Are there no tests for this which can be removed?

This can be merged tomorrow (24 hours after the Heimdall-UI release has been done as that will ensure everyone will be on the latest javascript).

**Comment by nl-ria** [comment]
There are no tests in this repo. I am going to merge this.

**Pull request merged**
